import Head from 'next/head';
import Layout from '../../components/Layout';
import GrantWritingService from '../../components/Services/GrantWritingService';

const grant_writing_service = () => {
    return (
        <>
            <Head>
                <title>Grant Writing Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Layout>
                <div>
                    <GrantWritingService />
                </div>
            </Layout>
            
        </>
    );
};

export default grant_writing_service;