import Head from 'next/head';
import Layout from '../../components/Layout';
import Login from '../../components/Shared/Login/Login';

const index = () => {
    return (
        <>
          <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <Layout>
                <div className='my-5'>
                    <Login />
                </div>
            </Layout>  
        </>
    );
};

export default index;