import Head from 'next/head';
import Layout from '../../components/Layout';
import Instructor from '../../components/HomePage/Course/Instructor';
import Instructorpage from '../../components/Instructorpage/Instructorpage';

const index = () => {
    return (
        <>
            <Head>
                <title>Instructor Info</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <Layout>
                    <div className='my-5'>
                        <Instructor />
                        <Instructorpage />
                    </div>
                </Layout>
            </div>
        </>
    );
};

export default index;